/camera/ob_camera_node:
  ros__parameters:
    # enable_point_cloud: false
    enable_colored_point_cloud: false
    enable_d2c_viewer: false
    enable_color: true
    enable_depth: true
    enable_ir: true
    enable_accel: false
    enable_gyro: false
    enable_laser: true
    depth_registration: true
    color_width: 1280
    color_height: 720
    color_fps: 30
    ir_width: 640
    ir_height: 576
    ir_fps: 30
    depth_width: 640
    depth_height: 576
    depth_fps: 30
    color_format: MJPG
    enable_frame_sync: true
    enable_point_cloud: true
    enable_sync_output_accel_gyro: true
    sync_mode: standalone
    # enable_color_auto_exposure: false

