/weed_detection:
  ros__parameters:
    publish_color: true
    color_resolution: 5
    cluster_distance: 10.0
    scale_z: 2.0
    split_size: 5000
    exg_threshold: -25.0
    nir_threshold: 70.0
    save_images: true
    x_lower: -0.50
    x_upper: -0.30
    x_off: 0.002
    y_off: -0.002
    z_off: 0.02
    collision_off: 0.05
    old_version: true
    dilation_size: 20
    wait_led: 1500
    wait_shock: 1000