/weed_detection:
  ros__parameters:
    cluster_distance: 10.0
    scale_z: 2.0
    split_size: 5000
    exg_threshold: -25.0
    nir_threshold: 80.0
    save_images: true
    dilation_size: 20
    x_lower: -0.50
    x_upper: -0.30
    x_off: 0.01
    y_off: 0.01
    z_off: 0.02