/weed_detection:
  ros__parameters:
    do_classification: true
    main_crop: 2473  # 2473: maize, 2354: sugar beet
    model: base

/weed_main:
  ros__parameters:
    save_runs: true
    publish_color: false
    color_resolution: 5
    exg_threshold: 0.0
    nir_threshold: 100.0
    ndvi_threshold: 0.0
    x_lower: -0.55
    x_upper: 0.38
    y_lower: -0.4
    y_upper: 0.4
    z_lower: 0.0
    z_upper: 0.4
    x_off: 0.002
    y_off: -0.002
    z_off: 0.02
    collision_off: 0.05
    old_version: true
    dilation_size: 20
    auto_exposure: false
    illumination_correction: true
    wait_shock: 200
    runs_folder: /home/ofa/ros2_ws/src/ros-weed-control/runs
    mock_images: mock_images_5