/arm_moveit:
  ros__parameters:
    motor1:
      - -0.028
      - -0.209
      - -0.028
      - -0.209
      - -0.028
      - -0.209
    motor2:
      - -0.073
      - -0.022
      - -0.073
      - -0.022
      - -0.073
      - -0.022
    motor3:
      - 2.040
      - 2.092
      - 2.040
      - 2.092
      - 2.040
      - 2.092