# specifies joint limits for MoveIt and URDF description

joint_limits:
  joint1:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint2:
    has_position_limits: true
    min_position: -2.1
    max_position: 2.1
    has_velocity_limits: true
    max_velocity: 20.0
    has_acceleration_limits: true
    max_acceleration: 20.0
  joint3:
    has_position_limits: true
    min_position: -6
    max_position: 6
    has_velocity_limits: true
    max_velocity: 20.0
    has_acceleration_limits: true
    max_acceleration: 20.0