# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 5  # Hz

    ofa_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

ofa_robot_controller:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    
    joints:
      - joint1
      - joint2
      - joint3
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity