sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 0.8
  filtered_cloud_topic: filtered_cloud
  image_topic: /depth_raw
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.2
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2