<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="weed_robot" params="parent">

    <!-- Axis dimensions -->
    <xacro:property name="axis_l" value="1.216" />
    <xacro:property name="axis_w" value="0.06" />
    <xacro:property name="axis_h" value="0.072" />

    <!-- Collision boxes -->
    <xacro:property name="frame_l" value="1.3" />
    <xacro:property name="frame_w" value="0.9" />
    <xacro:property name="frame_h" value="0.03" />
    <xacro:property name="box_w" value="0.01" />

    <!-- Side (Wheels) -->
    <xacro:property name="frame_l" value="1.3" />
    <xacro:property name="frame_w" value="0.8" />
    <xacro:property name="frame_h" value="0.03" />

    <!-- Frame dimensions -->
    <xacro:property name="frame_l" value="1.3" />
    <xacro:property name="frame_w" value="0.8" />
    <xacro:property name="frame_h" value="0.03" />

    <!-- Distance between carriage hard stop and end of axis -->
    <xacro:property name="carriage_off" value="${axis_l-0.116-1}" />

    <!-- Distance between axis carriage and center of first motor -->
    <xacro:property name="attachment_off" value="${0.06+0.002}" />

    <!-- Distance between ground and top of axis -->
    <xacro:property name="height" value="${0.68}" />

    <!-- Distance between motor and tube -->
    <xacro:property name="tube_off" value="${0.01}" />

    <!-- Motor dimensions -->
    <xacro:property name="motor_r" value="${0.089/2}" />
    <xacro:property name="motor_h" value="0.05025" />

    <!-- Offset between center of motor and center of carriage in x-direction -->
    <xacro:property name="motor_off" value="${0.0026}" />

    <!-- Camera enclosure dimensions -->
    <xacro:property name="camera_shield_w" value="0.12" />
    <xacro:property name="camera_shield_h" value="0.08" />
    <xacro:property name="camera_shield_l" value="0.048" />
    <xacro:property name="camera_shield_wall" value="0.002" />

    <!-- Offset between camera enclosure and motor center -->
    <xacro:property name="camera_shield_off_x" value="${motor_h/2+0.04355}" />
    <xacro:property name="camera_shield_off_y" value="${0.044}" />

    <!-- Camera dimensions -->
    <xacro:property name="camera_w" value="0.11526" />
    <xacro:property name="camera_h" value="0.06525" />
    <xacro:property name="camera_l" value="0.04026" />
    <xacro:property name="camera_off_y" value="0.00045" />
    <xacro:property name="camera_off_z" value="0.00615" />

    <!-- Offset between camera and optical center of rgb camera -->
    <xacro:property name="color_off_y" value="0.03" />
    <xacro:property name="color_off_z" value="0.05659361" />

    <!-- Tube dimensions -->
    <xacro:property name="arm_r" value="${0.045/2}" />
    <xacro:property name="arm1_l" value="0.368" />
    <xacro:property name="arm2_l" value="0.17" />

    <!-- End effector dimensions -->
    <xacro:property name="end_base_r" value="0.013" />
    <xacro:property name="end_base_l" value="0.15" />
    <xacro:property name="end_tip_r" value="0.003" />
    <xacro:property name="end_tip_l" value="0.05" />

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 ${height}" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="base_link" />
    </joint>
    <link name="base_link">
      <visual>
        <origin xyz="0 0 ${-axis_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${axis_l} ${axis_w} ${axis_h}" />
        </geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-axis_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${axis_l} ${axis_w} ${axis_h}" />
        </geometry>
      </collision>
      <!-- Top (Frame) -->
      <collision>
        <origin xyz="0 0 ${-frame_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${frame_l} ${frame_w} ${frame_h}" />
        </geometry>
      </collision>
      <!-- Side (Wheels) -->
      <collision>
        <origin xyz="0 ${-frame_w/2-box_w/2} ${-height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${frame_l} ${box_w} ${height}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 ${frame_w/2+box_w/2} ${-height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${frame_l} ${box_w} ${height}" />
        </geometry>
      </collision>
      <!-- Bottom (Ground) -->
      <collision>
        <origin xyz="0 0 ${-height-box_w/2}" rpy="0 0 0" />
        <geometry>
          <box size="${frame_l} ${frame_w} ${box_w}" />
        </geometry>
      </collision>
    </link>

    <joint name="joint1" type="prismatic">
      <origin xyz="${-axis_l/2+carriage_off-motor_off} 0 ${-axis_h-attachment_off}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="link1" />
      <axis xyz="-1 0 0" />
      <limit lower="${joint_limits['joint1']['min_position']}" upper="${joint_limits['joint1']['max_position']}"
      velocity="${joint_limits['joint1']['max_velocity']}" effort="100" />
    </joint>

    <link name="link1">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${motor_h}" radius="${motor_r}" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${motor_h}" radius="${motor_r}" />
        </geometry>
      </collision>
    </link>

    <joint name="camera_shield_joint" type="fixed">
      <origin xyz="${-camera_shield_off_x-camera_shield_l/2} ${-camera_shield_off_y} ${attachment_off}" rpy="0 0 0" />
      <parent link="link1" />
      <child link="camera_shield_link" />
    </joint>

    <link name="camera_shield_link">
      <visual>
        <origin xyz="0 ${-camera_shield_w/2+camera_shield_wall/2} ${-camera_shield_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_shield_l} ${camera_shield_wall} ${camera_shield_h}" />
        </geometry>
        <material name="grey"/>
      </visual>
      <visual>
        <origin xyz="0 ${camera_shield_w/2-camera_shield_wall/2} ${-camera_shield_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_shield_l} ${camera_shield_wall} ${camera_shield_h}" />
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 ${-camera_shield_w/2+camera_shield_wall/2} ${-camera_shield_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_shield_l} ${camera_shield_wall} ${camera_shield_h}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 ${camera_shield_w/2-camera_shield_wall/2} ${-camera_shield_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_shield_l} ${camera_shield_wall} ${camera_shield_h}" />
        </geometry>
      </collision>
    </link>

    <joint name="camera_joint" type="fixed">
      <origin xyz="0 ${-camera_off_y} ${-camera_off_z}" rpy="0 0 0" />
      <parent link="camera_shield_link" />
      <child link="camera_link" />
    </joint>

    <link name="camera_link">
      <visual>
        <origin xyz="0 0 ${-camera_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_l} ${camera_w} ${camera_h}" />
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-camera_h/2}" rpy="0 0 0" />
        <geometry>
          <box size="${camera_l} ${camera_w} ${camera_h}" />
        </geometry>
      </collision>
    </link>

    <joint name="camera_color_joint" type="fixed">
      <origin xyz="0 ${color_off_y} ${-color_off_z}" rpy="${pi} 0 ${pi/2}" />
      <parent link="camera_link" />
      <child link="camera_color_frame" />
    </joint>
    <link name="camera_color_frame" />

    <joint name="joint2" type="revolute">
      <origin xyz="${motor_h/2+tube_off+arm_r} 0 0" rpy="0 0 0" />
      <parent link="link1" />
      <child link="link2" />
      <axis xyz="1 0 0" />
      <limit lower="${joint_limits['joint2']['min_position']}" upper="${joint_limits['joint2']['max_position']}"
      velocity="${joint_limits['joint2']['max_velocity']}" effort="100" />
    </joint>

    <link name="link2">
      <visual>
        <origin xyz="0 0 ${-arm1_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${arm1_l}" radius="${arm_r}" />
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-arm1_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${arm1_l}" radius="${arm_r}" />
        </geometry>
      </collision>
    </link>

    <joint name="joint2_motor" type="fixed">
      <origin xyz="${-motor_h/2-tube_off-arm_r} 0 ${-arm1_l}" rpy="0 0 0" />
      <parent link="link2" />
      <child link="link2_motor" />
    </joint>

    <link name="link2_motor">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${motor_h}" radius="${motor_r}" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="${motor_h}" radius="${motor_r}" />
        </geometry>
      </collision>
    </link>

    <joint name="joint3" type="revolute">
      <origin xyz="${-motor_h/2-tube_off-arm_r} 0 0" rpy="${pi} 0 0" />
      <parent link="link2_motor" />
      <child link="link3" />
      <axis xyz="-1 0 0" />
      <limit lower="${joint_limits['joint3']['min_position']}" upper="${joint_limits['joint3']['max_position']}"
      velocity="${joint_limits['joint3']['max_velocity']}" effort="100" />
    </joint>

    <link name="link3">
      <visual>
        <origin xyz="0 0 ${-arm2_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${arm2_l}" radius="${arm_r}" />
        </geometry>
        <material name="orange"/>
      </visual>
      <visual>
        <origin xyz="0 0 ${-arm2_l-end_base_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${end_base_l}" radius="${end_base_r}" />
        </geometry>
        <material name="orange"/>
      </visual>
      <visual>
        <origin xyz="0 0 ${-arm2_l-end_base_l-end_tip_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${end_tip_l}" radius="${end_tip_r}" />
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-arm2_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${arm2_l}" radius="${arm_r}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${-arm2_l-end_base_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${end_base_l}" radius="${end_base_r}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${-arm2_l-end_base_l-end_tip_l/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${end_tip_l}" radius="${end_tip_r}" />
        </geometry>
      </collision>
    </link>

    <joint name="joint3_end" type="fixed">
      <origin xyz="0 0 ${-arm2_l-end_base_l-end_tip_l}" rpy="0 0 0" />
      <parent link="link3" />
      <child link="eef_link" />
    </joint>
    <link name="eef_link" />

	</xacro:macro>
  
</robot>
