<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="weed_robot" params="parent prefix">
	
	<xacro:property name="height" value="0.6" />
	<joint name="${prefix}base_joint" type="fixed">
		<origin xyz="0 0 ${height}" rpy="0 0 0" />
		<parent link="${parent}" />
		<child link="${prefix}base_link" />
	</joint>

	<xacro:property name="base_l" value="1.216" />
	<xacro:property name="base_w" value="0.06" />
	<xacro:property name="base_h" value="0.072" />
	<xacro:property name="base_m" value="5" />
	<link name="${prefix}base_link">
		<visual>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<geometry>
				<box size="${base_l} ${base_w} ${base_h}" />
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<geometry>
				<box size="${base_l} ${base_w} ${base_h}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<mass value="${base_m}" />
			<xacro:box_inertia m="${base_m}" x="${base_l}" y="${base_w}" z="${base_h}" />
		</inertial>
	</link>

	<xacro:property name="axis_length" value="1" />
	<joint name="${prefix}joint1" type="prismatic">
		<origin xyz="${-base_l/2+0.116} 0 ${-0.06-0.002}" rpy="0 0 0" />
		<parent link="${prefix}base_link" />
		<child link="${prefix}link1" />
		<axis xyz="1 0 0" />
		<limit lower="0" upper="${axis_length}" velocity="1" effort="10" />
	</joint>

	<xacro:property name="motor_r" value="${0.089/2}" />
	<xacro:property name="motor_h" value="0.05025" />
	<xacro:property name="motor_m" value="0.521" />
	<link name="${prefix}link1">
		<visual>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<geometry>
				<cylinder length="${motor_h}" radius="${motor_r}" />
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<geometry>
				<cylinder length="${motor_h}" radius="${motor_r}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<mass value="${motor_m}" />
			<xacro:cylinder_inertia m="${motor_m}" r="${motor_r}" h="${motor_h}" />
		</inertial>
	</link>

	<joint name="${prefix}joint2" type="revolute">
		<origin xyz="${motor_h/2+0.01} 0 0" rpy="0 0 0" />
		<parent link="${prefix}link1" />
		<child link="${prefix}link2" />
		<axis xyz="1 0 0" />
		<limit lower="${-pi/2}" upper="${pi/2}" velocity="5" effort="10" />
	</joint>

	<xacro:property name="arm_r" value="${0.045/2}" />
	<xacro:property name="arm_ri" value="${0.041/2}" />
	<xacro:property name="arm1_l" value="0.25" />
	<xacro:property name="arm1_m" value="${1650*(arm_r**2*pi-arm_ri**2*pi)*arm1_l}" />
	<xacro:property name="arm2_l" value="0.425" />
	<xacro:property name="arm2_m" value="${1650*(arm_r**2*pi-arm_ri**2*pi)*arm2_l}" />
	<link name="${prefix}link2">
		<visual>
			<origin xyz="${arm_r} 0 ${-arm1_l/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm1_l}" radius="${arm_r}" />
			</geometry>
			<material name="orange"/>
		</visual>
		<collision>
			<origin xyz="${arm_r} 0 ${-arm1_l/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm1_l}" radius="${arm_r}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="${arm_r} 0 ${-arm1_l/2}" rpy="0 0 0" />
			<mass value="${arm1_m}" />
			<xacro:cylinder_inertia m="${arm1_m}" r="${arm_r}" h="${arm1_l}" />
		</inertial>
	</link>

	<joint name="${prefix}joint2_motor" type="fixed">
		<origin xyz="${-motor_h/2-0.0058} 0 ${-arm1_l}" rpy="0 0 0" />
		<parent link="${prefix}link2" />
		<child link="${prefix}link2_motor" />
	</joint>

	<link name="${prefix}link2_motor">
		<visual>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<geometry>
				<cylinder length="${motor_h}" radius="${motor_r}" />
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<geometry>
				<cylinder length="${motor_h}" radius="${motor_r}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
			<mass value="${motor_m}" />
			<xacro:cylinder_inertia m="${motor_m}" r="${motor_r}" h="${motor_h}" />
		</inertial>
	</link>

	<joint name="${prefix}joint3" type="continuous">
		<origin xyz="${-motor_h/2-0.01} 0 0" rpy="0 0 0" />
		<parent link="${prefix}link2_motor" />
		<child link="${prefix}link3" />
		<axis xyz="1 0 0" />
		<limit lower="${-pi}" upper="${pi}" velocity="5" effort="10" />
	</joint>

	<link name="${prefix}link3">
		<visual>
			<origin xyz="${-arm_r} 0 ${-arm2_l/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm2_l}" radius="${arm_r}" />
			</geometry>
			<material name="orange"/>
		</visual>
		<collision>
			<origin xyz="${-arm_r} 0 ${-arm2_l/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm2_l}" radius="${arm_r}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="${-arm_r} 0 ${-arm2_l/2}" rpy="0 0 0" />
			<mass value="${arm2_m}" />
			<xacro:cylinder_inertia m="${arm2_m}" r="${arm_r}" h="${arm2_l}" />
		</inertial>
	</link>

	</xacro:macro>

	<!-- <xacro:property name="top_l" value="0.2" />
	<xacro:property name="top_w" value="0.2" />
	<xacro:property name="wheel_r" value="0.2" />
	<xacro:property name="wheel_l" value="0.1" />
	<xacro:property name="wheel_m" value="5" />
	<xacro:property name="top_h" value="${height-2*wheel_r}" />
	<xacro:macro name="wheel" params="prefix x y">
		<joint name="${prefix}_wheel_joint" type="fixed">
			<parent link="base_link" />
			<child link="${prefix}_wheel_link" />
			<origin xyz="${x} ${y} 0" rpy="0 0 0" />
		</joint>

		<link name="${prefix}_wheel_link">
			<visual>
				<origin xyz="0 0 ${-top_h/2}" rpy="0 0 0"/>
				<geometry>
					<box size="${top_l} ${top_w} ${top_h}" />
				</geometry>
				<material name="blue"/>
			</visual>
			<visual>
				<origin xyz="0 0 ${-top_h-wheel_r}" rpy="${pi/2} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_r}" length="${wheel_l}" />
				</geometry>
				<material name="blue"/>
			</visual>
			<collision>
				<origin xyz="0 0 ${-top_h/2-wheel_r}" rpy="0 0 0"/>
				<geometry>
					<box size="${top_l} ${2*wheel_r} ${top_h+2*wheel_r}" />
				</geometry>
			</collision>
			<inertial>
				<origin xyz="0 0 ${-top_h/2-wheel_r}" rpy="0 0 0"/>
				<mass value="${wheel_m}" />
				<xacro:box_inertia m="${wheel_m}" x="${top_w}" y="${2*wheel_r}" z="${top_h+2*wheel_r}" />
			</inertial>
		</link>
	</xacro:macro>

	<xacro:wheel prefix="fl" x="${base_l/2-top_w/2}" y="${base_w/2-top_l/2}" />
	<xacro:wheel prefix="bl" x="${-base_l/2+top_w/2}" y="${base_w/2-top_l/2}" />
	<xacro:wheel prefix="fr" x="${base_l/2-top_w/2}" y="${-base_w/2+top_l/2}" />
	<xacro:wheel prefix="br" x="${-base_l/2+top_w/2}" y="${-base_w/2+top_l/2}" /> -->
</robot>
